name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using your repository secrets
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build . --tag ehsadu/eventmanagement:latest

      # Step 4: Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ehsadu/eventmanagement:latest
